-- CASA DOCE — Higienização dos Carrinhos: redesenho (29/07).
-- Nutricionista esclareceu: NÃO é registro obrigatório da Anvisa, é só
-- controle interno; na prática todos os carrinhos são higienizados no MESMO
-- DIA (não em datas diferentes). O modelo antigo pedia data+assinatura por
-- carrinho (32x) — fricção real (ela relatou "sempre esquecem de preencher").
-- Agora: 1 data + 1 responsável pro lote inteiro, e um checklist (checkbox)
-- de quais carrinhos foram feitos. Mesmo id — idempotente, atualiza in place.
insert into public.form_templates (id, tenant_id, category, frequency, title, description, sections, updated_at) values
  ('0be8daac-24a5-461b-af6c-f438edcf5f48','bf245c3b-2f9','faxina','biweekly','Higienização dos Carrinhos','Controle interno de limpeza (não é registro obrigatório da Anvisa). Higienização quinzenal, feita no mesmo dia para todos os carrinhos — registre a data/responsável uma vez e marque os que foram higienizados.','[{"id":"cd-carr-reg","title":"Registro","fields":[{"id":"cd-carr-data","label":"Data da higienização","type":"date"},{"id":"cd-carr-resp","label":"Responsável","type":"text"}]},{"id":"cd-carr-lav","title":"Carrinhos higienizados","fields":[{"id":"cd-carr-T1","label":"Carrinho T1","type":"checkbox"},{"id":"cd-carr-T2","label":"Carrinho T2","type":"checkbox"},{"id":"cd-carr-T3","label":"Carrinho T3","type":"checkbox"},{"id":"cd-carr-T4","label":"Carrinho T4","type":"checkbox"},{"id":"cd-carr-T5","label":"Carrinho T5","type":"checkbox"},{"id":"cd-carr-T6","label":"Carrinho T6","type":"checkbox"},{"id":"cd-carr-T7","label":"Carrinho T7","type":"checkbox"},{"id":"cd-carr-E1","label":"Carrinho E1","type":"checkbox"},{"id":"cd-carr-E2","label":"Carrinho E2","type":"checkbox"},{"id":"cd-carr-B1","label":"Carrinho B1","type":"checkbox"},{"id":"cd-carr-B2","label":"Carrinho B2","type":"checkbox"},{"id":"cd-carr-B3","label":"Carrinho B3","type":"checkbox"},{"id":"cd-carr-C1","label":"Carrinho C1","type":"checkbox"},{"id":"cd-carr-C2","label":"Carrinho C2","type":"checkbox"},{"id":"cd-carr-C3","label":"Carrinho C3","type":"checkbox"},{"id":"cd-carr-F1","label":"Carrinho F1","type":"checkbox"},{"id":"cd-carr-F2","label":"Carrinho F2","type":"checkbox"},{"id":"cd-carr-F3","label":"Carrinho F3","type":"checkbox"},{"id":"cd-carr-F4","label":"Carrinho F4","type":"checkbox"},{"id":"cd-carr-F5","label":"Carrinho F5","type":"checkbox"},{"id":"cd-carr-F6","label":"Carrinho F6","type":"checkbox"},{"id":"cd-carr-F7","label":"Carrinho F7","type":"checkbox"},{"id":"cd-carr-F8","label":"Carrinho F8","type":"checkbox"},{"id":"cd-carr-F9","label":"Carrinho F9","type":"checkbox"},{"id":"cd-carr-F10","label":"Carrinho F10","type":"checkbox"},{"id":"cd-carr-F11","label":"Carrinho F11","type":"checkbox"},{"id":"cd-carr-F12","label":"Carrinho F12","type":"checkbox"},{"id":"cd-carr-A1","label":"Carrinho A1","type":"checkbox"},{"id":"cd-carr-A2","label":"Carrinho A2","type":"checkbox"},{"id":"cd-carr-A3","label":"Carrinho A3","type":"checkbox"},{"id":"cd-carr-A4","label":"Carrinho A4","type":"checkbox"},{"id":"cd-carr-A5","label":"Carrinho A5","type":"checkbox"}]},{"id":"cd-carr-obs","title":"Observações","fields":[{"id":"cd-carr-obs-t","label":"Observações","type":"text"}]}]'::jsonb, now())
on conflict (id) do update set category=excluded.category, frequency=excluded.frequency, title=excluded.title, description=excluded.description, sections=excluded.sections, updated_at=now();
