-- CASA DOCE — Fase C (29/07): respostas da nutricionista.
-- 1) 3 templates novos: Higiene Pessoal, Vetores (customizado), Dedetização —
--    a CASA DOCE não tinha nenhum dos três ainda (só as 8 planilhas da Fase B).
-- 2) 2 templates existentes ganharam um campo/seção a mais (mesmo id — o
--    on conflict atualiza in place, sem duplicar): Banheiros ganhou bloco de
--    não conformidade (não tinha nenhum); Hortifrutícolas ganhou o campo
--    "Responsável pela correção" que faltava na não conformidade.
-- Idempotente. Mesmos uuids do seed em forms.jsx.

insert into public.form_templates (id, tenant_id, category, frequency, title, description, sections, updated_at) values

  -- Banheiros — atualização: + bloco de não conformidade
  ('c61acf39-5ff8-404e-8fae-f9f68734f1b2','bf245c3b-2f9','faxina','daily','Controle de Higienização de Banheiros','Registro diário. Marque a atividade realizada e o horário; quem preenche fica identificado (assinatura digital). Ref.: FP.HIG.001.','[{"id":"cd-ban-lg","title":"Limpeza Geral","fields":[{"id":"cd-ban-lg-feito","label":"Realizada","type":"checkbox","hint":"Limpeza geral do banheiro"},{"id":"cd-ban-lg-hora","label":"Horário","type":"text","hint":"Hora em que foi feita"}]},{"id":"cd-ban-mn","title":"Manutenção","fields":[{"id":"cd-ban-mn-feito","label":"Realizada","type":"checkbox","hint":"Reposição de papel, sabonete, etc."},{"id":"cd-ban-mn-hora","label":"Horário","type":"text","hint":"Hora em que foi feita"},{"id":"cd-ban-obs","label":"Observações","type":"text"}]},{"id":"cd-ban-nc","title":"Não conformidade (se houver)","fields":[{"id":"cd-ban-ncdesc","label":"Não conformidade","type":"text"},{"id":"cd-ban-ncacao","label":"Ação corretiva","type":"text"},{"id":"cd-ban-ncresp","label":"Responsável pela correção","type":"text"}]}]'::jsonb, now()),

  -- Hortifrutícolas — atualização: + campo Responsável na não conformidade
  ('f565a332-b2a1-401d-b1f4-5e70825aafec','bf245c3b-2f9','faxina','daily','Higienização de Hortifrutícolas','Registro da higienização de hortifrutícolas (imersão em solução sanitizante). Frequência: diária (a confirmar com a RT).','[{"id":"cd-hf-reg","title":"Registro","fields":[{"id":"cd-hf-data","label":"Data","type":"date_sig"},{"id":"cd-hf-item","label":"Hortifrutícola","type":"text","hint":"Ex.: alface, morango"},{"id":"cd-hf-sol","label":"Solução utilizada","type":"text","hint":"Ex.: hipoclorito 200 ppm"},{"id":"cd-hf-tempo","label":"Tempo de imersão (min)","type":"number"}]},{"id":"cd-hf-nc","title":"Não conformidade (se houver)","fields":[{"id":"cd-hf-ncdesc","label":"Não conformidade","type":"text"},{"id":"cd-hf-ncacao","label":"Ação corretiva","type":"text"},{"id":"cd-hf-ncresp","label":"Responsável pela correção","type":"text"}]}]'::jsonb, now()),

  -- Higiene Pessoal — novo
  ('c1e7838e-1cac-4a76-a0c3-296e1bebbfdb','bf245c3b-2f9','higiene_pessoal','daily','Higiene Pessoal dos Colaboradores','Verificação diária de higiene, uniforme, comportamento e EPI. C=conforme / NC=não conforme.','[{"id":"cd-hig-ver","title":"Verificação","fields":[{"id":"cd-hig-uniforme","label":"Uniforme","type":"cnc"},{"id":"cd-hig-sapato","label":"Sapato","type":"cnc"},{"id":"cd-hig-cabelo","label":"Cabelo","type":"cnc"},{"id":"cd-hig-barba","label":"Barba","type":"cnc"},{"id":"cd-hig-unha","label":"Unha","type":"cnc"},{"id":"cd-hig-adorno","label":"Adorno","type":"cnc","hint":"Remover brincos, anéis, pulseiras, colares"},{"id":"cd-hig-comport","label":"Comportamento","type":"cnc","hint":"Atitudes higiênicas, não manipular objetos fora da atividade"},{"id":"cd-hig-avental","label":"Avental","type":"cnc"},{"id":"cd-hig-perfume","label":"Perfume","type":"cnc","hint":"Ausência de perfume forte"},{"id":"cd-hig-ferim","label":"Ferimento","type":"cnc","hint":"Ferimentos devidamente cobertos"},{"id":"cd-hig-maos","label":"Lavar Mãos","type":"cnc","hint":"Ao iniciar, usar banheiro, trocar atividade, colocar luvas"},{"id":"cd-hig-obs","label":"Observações","type":"text"}]}]'::jsonb, now()),

  -- Vetores e Pragas — novo (customizado: setor de destinação, sem Pombo, com Abelha)
  ('96496ddc-a938-4b90-9aa5-fd5710a54fb0','bf245c3b-2f9','vetores_pragas','daily','Controle Integrado de Vetores e Pragas','Verificação diária. Registrar tipo de praga e o setor onde foi feito o controle. Anexar comprovante de dedetização.','[{"id":"cd-vet-ocorr","title":"Ocorrências do dia","fields":[{"id":"cd-vet-abelha","label":"Abelha (A)","type":"presence","hint":"Setor: Padaria / Café / Gelateria / Confeitaria"},{"id":"cd-vet-barata","label":"Barata (B)","type":"presence","hint":"Setor: Padaria / Café / Gelateria / Confeitaria"},{"id":"cd-vet-formiga","label":"Formiga (F)","type":"presence","hint":"Setor: Padaria / Café / Gelateria / Confeitaria"},{"id":"cd-vet-mosca","label":"Mosca / Mosquito (M)","type":"presence","hint":"Setor: Padaria / Café / Gelateria / Confeitaria"},{"id":"cd-vet-roedor","label":"Roedor (R)","type":"presence","hint":"Setor: Padaria / Café / Gelateria / Confeitaria"},{"id":"cd-vet-acao","label":"Ação tomada","type":"text"},{"id":"cd-vet-obs","label":"Observações","type":"text"}]}]'::jsonb, now()),

  -- Dedetização — novo
  ('17ce4089-0e51-48a7-991a-bdde090a33e9','bf245c3b-2f9','dedetizacao','monthly','Controle de Dedetização','Registrar empresa, data, serviço e produto. Anexar comprovante.','[{"id":"cd-ded-reg","title":"Registro do serviço","fields":[{"id":"cd-ded-emp","label":"Empresa executora","type":"text"},{"id":"cd-ded-data","label":"Data do serviço","type":"text"},{"id":"cd-ded-serv","label":"Serviço executado","type":"text"},{"id":"cd-ded-prod","label":"Produto utilizado","type":"text"},{"id":"cd-ded-cert","label":"Número do certificado","type":"text"},{"id":"cd-ded-obs","label":"Observações","type":"text"}]}]'::jsonb, now())

on conflict (id) do update set category=excluded.category, frequency=excluded.frequency, title=excluded.title, description=excluded.description, sections=excluded.sections, updated_at=now();
